language: java
sudo: false
install: True
      
addons:
  sonarqube:
      
jdk:
  - oraclejdk8

script:
    # JaCoC  is  used to have code coverage,  agent has to be
    - mvn -T 4 -q -DskipTests -Pmesos -Pyarn -Phadoop-2.3 -Pkinesis-asl -Phive -Phive-thriftserver install sonar:sonar
    
    - dev/lint-java

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false  
