language: java
sudo: false
install: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar checkstyle:check
addons:
  sonarqube:
      
jdk:
  - oraclejdk8

script:
    # JaCoC  is  used to have code coverage,  agent has to be activated
    - dev/lint-java

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false  
