language: java
sudo: false
install: true

addons:
  sonarqube:
      
jdk:
  - oraclejdk8

script:
    # JaCoC  is  used to have code coverage, the agent has to be activated
  - mvn install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - dev/lint-java

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false  
